"""Document formatter for resumes (.docx) and cover letters (.pdf).

Parses JSON resume output from the LLM and renders:
- Resumes as .docx using python-docx (matching the original resume styling)
- Cover letters as .pdf using fpdf2
"""

import io
import json
import re

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


# ── Docx styling constants ───────────────────────────────────────────────────

NAME_SIZE = Pt(14)
CONTACT_SIZE = Pt(10)
SECTION_HEADER_SIZE = Pt(10.5)
JOB_TITLE_SIZE = Pt(10)
BODY_SIZE = Pt(10)
SKILL_SIZE = Pt(10)

FONT_NAME = "Calibri"
SECTION_SPACING_BEFORE = Pt(6)
BULLET_SPACING = Pt(1)


# ── JSON extraction ─────────────────────────────────────────────────────────

def _extract_json(text: str) -> dict:
    """Extract JSON from LLM response, stripping markdown fences or preamble."""
    text = text.strip()
    # Strip markdown code fences
    text = re.sub(r"^```(?:json)?\s*\n?", "", text)
    text = re.sub(r"\n?```\s*$", "", text)
    text = text.strip()

    # Find the JSON object
    start = text.find("{")
    if start == -1:
        raise ValueError(f"No JSON object found. Response starts with: {text[:200]!r}")

    # Find matching closing brace
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                json_str = text[start:i + 1]
                try:
                    return json.loads(json_str)
                except json.JSONDecodeError as e:
                    raise ValueError(
                        f"Invalid JSON: {e}. First 300 chars: {json_str[:300]!r}"
                    ) from e

    raise ValueError(f"Unterminated JSON object. First 300 chars: {text[:300]!r}")


# ── Docx helpers ─────────────────────────────────────────────────────────────

def _set_paragraph_spacing(paragraph, before=Pt(0), after=Pt(0)):
    pf = paragraph.paragraph_format
    pf.space_before = before
    pf.space_after = after


def _add_bottom_border(paragraph):
    pPr = paragraph._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "4")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "000000")
    pBdr.append(bottom)
    pPr.append(pBdr)


def _add_run(paragraph, text, bold=False, italic=False, size=BODY_SIZE, font=FONT_NAME):
    run = paragraph.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = size
    run.font.name = font
    return run


def _add_section_header(doc, title):
    p = doc.add_paragraph()
    _set_paragraph_spacing(p, before=SECTION_SPACING_BEFORE, after=Pt(2))
    _add_run(p, title.upper(), bold=True, size=SECTION_HEADER_SIZE)
    _add_bottom_border(p)
    return p


def _add_bullet(doc, text, spacing_after=BULLET_SPACING):
    p = doc.add_paragraph(style="List Bullet")
    _set_paragraph_spacing(p, before=Pt(0), after=spacing_after)
    run = p.runs[0] if p.runs else p.add_run()
    run.text = ""
    _add_run(p, text, size=BODY_SIZE)
    return p


# ── Static sections (not generated by LLM) ─────────────────────────────────

STATIC_HEADER = {
    "name": "Satya Chamana",
    "contact": {
        "phone": "616-426-7409",
        "email": "satyachamana@gmail.com",
        "location": "Fremont, CA",
        "linkedin": "linkedin.com/in/satya-chamana",
        "portfolio": "satyachamana.com",
        "github": "github.com/SatyaChamana",
    },
}

STATIC_CERTIFICATIONS = [
    "SAS Certified Associate",
    "Infosys Certified Python Developer",
    "Infosys Certified React JS Developer",
    "Infosys Certified Agile Developer",
    "AI 501 Introduction to AI (Non-Degree, GVSU)",
    "AI 502 Generative AI (Non-Degree, GVSU)",
]

STATIC_EDUCATION = [
    {
        "name": "Master of Science in Data Science and Analytics",
        "institution": "Grand Valley State University",
        "gpa": "3.9/4.0",
    },
    {
        "name": "Bachelor of Technology in Mechanical Engineering",
        "institution": "JNTU Kakinada",
        "gpa": "8.1/10",
    },
]

STATIC_PROJECTS = [
    {
        "name": "RAG-Powered Healthcare Chatbot",
        "technologies": "Ollama, LangChain, ChromaDB, FAISS, HPC, Python",
        "bullets": [
            "Architected a Retrieval-Augmented Generation pipeline on university HPC cluster for processing and querying institutional knowledge bases with natural language",
            "Implemented structured JSON output enforcement for reliable downstream integration with clinical and administrative systems",
            "Designed modular pipeline architecture enabling swap of embedding models and LLM backends without code changes",
        ],
    },
    {
        "name": "Robust EEG Decoding with Dynamic Data Evolution",
        "technologies": "Python, Deep Learning, WGF, DRO",
        "bullets": [
            "Designed a principled data evolution framework using Wasserstein Gradient Flow (WGF) to improve robustness in EEG decoding tasks, addressing a critical challenge in brain-computer interface research",
            "Applied distributionally robust optimization (DRO) to train models across evolved data distributions, mitigating overfitting on small and noisy EEG/biomedical datasets",
            "Achieved state-of-the-art performance on corrupted EEG signals, outperforming competitive baselines and demonstrating generalization across distribution shifts",
        ],
    },
    {
        "name": "Hospital Readmission Analytics Dashboard",
        "technologies": "Azure SQL Database, SQL Server, Power BI, DAX",
        "bullets": [
            "Designed and deployed a star schema data model on Azure SQL Database with fact and dimension tables, writing SQL scripts for schema creation, data loading, and transformation (window functions, CASE logic)",
            "Built four-page interactive Power BI dashboard (Executive Summary, Readmission Deep Dive, Financial Performance, Patient Demographics) with 20+ DAX measures covering readmission rates, avg length of stay, cost per admission, and payer mix",
        ],
    },
    {
        "name": "Student Early Warning System",
        "technologies": "Python, XGBoost, Scikit-learn",
        "bullets": [
            "Built ML classification system analyzing GPA trends, attendance patterns, and engagement metrics to predict at-risk students with 92% accuracy",
            "Reduced manual review workload by 60% across 500+ student records, enabling early intervention by academic advisors",
        ],
    },
    {
        "name": "FuelFlow: Drive-Thru Vehicle Time and Fuel Analysis",
        "technologies": "Python, YOLOv8, OpenCV, DeepSORT",
        "bullets": [
            "Built computer vision pipeline to detect, track, and classify vehicles in real-time using YOLOv8 for detection and DeepSORT for multi-object tracking",
            "Estimated wait time and idle fuel consumption by vehicle type, quantifying environmental impact and providing data-driven optimization recommendations",
        ],
    },
]

STATIC_AWARDS = [
    "Infosys MVP Award",
    "Infosys Best Team Award",
    "Dean's Scholarship at Grand Valley State University",
]


# ── Resume DOCX from JSON ───────────────────────────────────────────────────

def format_resume_docx(text: str) -> bytes:
    """Parse JSON resume (summary + skills + experience from LLM) and render a full .docx."""
    data = _extract_json(text)
    doc = Document()

    # Set narrow margins
    for section in doc.sections:
        section.top_margin = Inches(0.5)
        section.bottom_margin = Inches(0.5)
        section.left_margin = Inches(0.5)
        section.right_margin = Inches(0.5)

    # Set default font
    style = doc.styles["Normal"]
    style.font.name = FONT_NAME
    style.font.size = BODY_SIZE
    style.paragraph_format.space_before = Pt(0)
    style.paragraph_format.space_after = Pt(0)

    # ── Header: Name & Contact (static) ──
    header = STATIC_HEADER
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_paragraph_spacing(p, after=Pt(1))
    _add_run(p, header["name"], bold=True, size=NAME_SIZE)

    contact = header["contact"]
    parts = [contact[k] for k in ["phone", "email", "location", "linkedin", "portfolio", "github"] if contact.get(k)]
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_paragraph_spacing(p, after=Pt(2))
    _add_run(p, " | ".join(parts), size=CONTACT_SIZE)

    # ── Professional Summary (from LLM) ──
    summary = data.get("summary", {})
    angle = summary.get("angle", "")
    bullets = summary.get("bullets", [])
    if angle or bullets:
        _add_section_header(doc, "Professional Summary")
        if angle:
            p = doc.add_paragraph()
            _set_paragraph_spacing(p, after=Pt(2))
            _add_run(p, angle, size=BODY_SIZE)
        for bullet in bullets:
            _add_bullet(doc, bullet)

    # ── Technical Skills (from LLM) ──
    skills = data.get("skills", [])
    if skills:
        _add_section_header(doc, "Technical Skills")
        for cat in skills:
            label = cat.get("name", "")
            items = cat.get("items", "")
            if not items:
                continue
            p = doc.add_paragraph()
            _set_paragraph_spacing(p, after=Pt(1))
            _add_run(p, f"{label}: ", bold=True, size=SKILL_SIZE)
            _add_run(p, items, size=SKILL_SIZE)

    # ── Certifications (static) ──
    _add_section_header(doc, "Certifications")
    for item in STATIC_CERTIFICATIONS:
        _add_bullet(doc, item)

    # ── Professional Experience (from LLM) ──
    experience = data.get("experience", [])
    if experience:
        _add_section_header(doc, "Professional Experience")
        for i, job in enumerate(experience):
            title = job.get("title", "")
            company = job.get("company", "")
            location = job.get("location", "")
            dates = job.get("dates", "")

            left = title
            if company:
                left += " | " + company

            right_parts = []
            if location:
                right_parts.append(location)
            if dates:
                right_parts.append(dates)
            right = " | ".join(right_parts)

            p = doc.add_paragraph()
            spacing_before = Pt(6) if i > 0 else Pt(2)
            _set_paragraph_spacing(p, before=spacing_before, after=Pt(0))

            _add_run(p, left, bold=True, size=JOB_TITLE_SIZE)

            if right:
                _add_run(p, "\t" + right, size=BODY_SIZE)
                tab_stops = p.paragraph_format.tab_stops
                tab_stops.add_tab_stop(Inches(7.0), alignment=WD_ALIGN_PARAGRAPH.RIGHT)

            for bullet in job.get("bullets", []):
                _add_bullet(doc, bullet)

    # ── Education (static) ──
    _add_section_header(doc, "Education")
    for deg in STATIC_EDUCATION:
        name = deg["name"]
        institution = deg["institution"]
        gpa = deg.get("gpa", "")

        left = f"{name} - {institution}"
        right = f"GPA: {gpa}" if gpa else ""

        p = doc.add_paragraph()
        _set_paragraph_spacing(p, after=Pt(1))
        _add_run(p, left, bold=True, size=BODY_SIZE)

        if right:
            _add_run(p, f"\t{right}", size=BODY_SIZE)
            tab_stops = p.paragraph_format.tab_stops
            tab_stops.add_tab_stop(Inches(7.0), alignment=WD_ALIGN_PARAGRAPH.RIGHT)

    # ── Projects (static) ──
    _add_section_header(doc, "Projects")
    for proj in STATIC_PROJECTS:
        p = doc.add_paragraph()
        _set_paragraph_spacing(p, before=Pt(2), after=Pt(1))
        _add_run(p, proj["name"], bold=True, size=BODY_SIZE)
        if proj.get("technologies"):
            _add_run(p, f" | {proj['technologies']}", italic=True, size=BODY_SIZE)
        for bullet in proj["bullets"]:
            _add_bullet(doc, bullet)

    # ── Awards (static) ──
    _add_section_header(doc, "Awards & Achievements")
    for item in STATIC_AWARDS:
        _add_bullet(doc, item)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ── Cover Letter PDF (unchanged) ─────────────────────────────────────────────

from fpdf import FPDF

PAGE_W = 210
MARGIN_X = 12.7
MARGIN_TOP = 12.7
MARGIN_BOTTOM = 12.7
CONTENT_W = PAGE_W - 2 * MARGIN_X
CL_BODY_SIZE = 9.5
CL_LINE_HEIGHT = 3.8


def _safe(text: str) -> str:
    if not text:
        return ""
    replacements = {
        '\u2014': '--', '\u2013': '-', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2022': '\xb7', '\u2026': '...',
        '\u2011': '-', '\u00a0': ' ',
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _new_pdf() -> FPDF:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_left_margin(MARGIN_X)
    pdf.set_right_margin(MARGIN_X)
    pdf.set_top_margin(MARGIN_TOP)
    pdf.set_auto_page_break(auto=True, margin=MARGIN_BOTTOM)
    pdf.add_page()
    return pdf


def format_cover_letter_pdf(text: str) -> bytes:
    """Render a cover letter with professional formatting."""
    pdf = _new_pdf()
    lines = text.strip().split("\n")

    greeting_idx = 0
    for i, line in enumerate(lines):
        if line.strip().lower().startswith("dear"):
            greeting_idx = i
            break

    for i in range(greeting_idx):
        line = lines[i].strip()
        if line:
            pdf.set_font("Helvetica", "", CL_BODY_SIZE)
            pdf.multi_cell(CONTENT_W, CL_LINE_HEIGHT, _safe(line), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    if greeting_idx > 0:
        pdf.ln(3)

    if greeting_idx < len(lines):
        pdf.set_font("Helvetica", "B", CL_BODY_SIZE + 0.5)
        pdf.multi_cell(CONTENT_W, CL_LINE_HEIGHT + 1, _safe(lines[greeting_idx].strip()), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    current_paragraph = []
    for line in lines[greeting_idx + 1:]:
        stripped = line.strip()
        if not stripped:
            if current_paragraph:
                _render_paragraph(pdf, " ".join(current_paragraph))
                current_paragraph = []
                pdf.ln(3)
        else:
            if stripped.lower() in ("sincerely,", "best regards,", "regards,", "respectfully,", "best,"):
                if current_paragraph:
                    _render_paragraph(pdf, " ".join(current_paragraph))
                    current_paragraph = []
                pdf.ln(5)
                pdf.set_font("Helvetica", "", CL_BODY_SIZE)
                pdf.cell(CONTENT_W, CL_LINE_HEIGHT, _safe(stripped), new_x="LMARGIN", new_y="NEXT")
            elif not current_paragraph and any(
                stripped.lower().startswith(s) for s in ["satya", "sincerely", "best", "regards"]
            ) and len(stripped.split()) <= 4:
                if current_paragraph:
                    _render_paragraph(pdf, " ".join(current_paragraph))
                    current_paragraph = []
                pdf.ln(1)
                pdf.set_font("Helvetica", "B", CL_BODY_SIZE)
                pdf.cell(CONTENT_W, CL_LINE_HEIGHT, _safe(stripped), new_x="LMARGIN", new_y="NEXT")
            else:
                current_paragraph.append(stripped)

    if current_paragraph:
        _render_paragraph(pdf, " ".join(current_paragraph))

    return bytes(pdf.output())


def _render_paragraph(pdf, text):
    pdf.set_font("Helvetica", "", CL_BODY_SIZE + 0.5)
    pdf.multi_cell(CONTENT_W, CL_LINE_HEIGHT + 0.8, _safe(text), new_x="LMARGIN", new_y="NEXT")
