scheduler:
  interval_minutes: 10

email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  sender_email: satyachamana@gmail.com
  sender_password: dvtf ukbg fglt zrtr
  recipient_email: satyajason143@gmail.com

storage:
  excel_file: "jobs.xlsx"

sites:
  - name: Salesforce
    enabled: true
    parser: salesforce
    url: "https://careers.salesforce.com/en/jobs/?search=Software&country=United+States+of+America&pagesize=30#results"
    target_titles:
      - "Software Engineer"

  - name: Salesforce
    enabled: true
    parser: salesforce
    url: "https://careers.salesforce.com/en/jobs/?search=Data&country=United+States+of+America&pagesize=30#results"
    target_titles:
      - "Data Scientist"
      - "Data Analyst"
      - "ML Engineer"

  - name: Airbnb
    enabled: true
    parser: airbnb
    url: "https://careers.airbnb.com/positions/?_search_input=software"
    target_titles:
      - "Software Engineer"

  - name: Adobe
    enabled: true
    parser: workday
    url: "https://careers.adobe.com/us/en/search-results?keywords=Software%2C%20data"
    workday_url: "https://adobe.wd5.myworkdayjobs.com/wday/cxs/adobe/external_experienced/jobs"
    search_text: "Software"
    limit: 20
    target_titles:
      - "Software Engineer"

  - name: Amex
    enabled: true
    parser: eightfold
    url: "https://aexp.eightfold.ai/careers?pid=40032366&domain=aexp.com&sort_by=relevance&hl=en"
    eightfold_domain: "aexp.eightfold.ai"
    eightfold_company_domain: "aexp.com"
    search_text: "software"
    search_location: "United States"
    limit: 20
    target_titles:
      - "Software Engineer"

  - name: Apple
    enabled: true
    parser: apple
    url: "https://jobs.apple.com/en-us/search?search=Software&sort=relevance&location=united-states-USA"
    target_titles:
      - "Software Engineer"

  - name: Cisco
    enabled: true
    parser: generic
    url: "https://jobs.cisco.com/jobs/SearchJobs/software?21178=%5B169482%5D&21178_format=6020&listFilterMode=1"
    wait_ms: 8000
    target_titles:
      - "Software Engineer"

  - name: Caterpillar
    enabled: true
    parser: caterpillar
    url: "https://careers.caterpillar.com/en/jobs/?search=Software#results"
    target_titles:
      - "Software Engineer"

  - name: Ford
    enabled: true
    parser: generic
    url: "https://jobs.ford.com/careers?query=Software&start=0&location=united+states&pid=563568450711045&sort_by=relevance&filter_include_remote=1"
    wait_ms: 8000
    target_titles:
      - "Software Engineer"

  - name: Meta
    enabled: true
    parser: meta
    url: "https://www.metacareers.com/jobs?query=software&is_leadership=0&offices[0]=United%20States"
    target_titles:
      - "Software Engineer"

  - name: PayPal
    enabled: true
    parser: generic
    url: "https://paypal.eightfold.ai/careers?query=software&start=0&location=united+states&pid=274917400223&sort_by=relevance&filter_include_remote=1"
    wait_ms: 8000
    target_titles:
      - "Software Engineer"

  - name: Microsoft
    enabled: true
    parser: microsoft
    url: "https://jobs.careers.microsoft.com/global/en/search?q=SDE&lc=United%20States&l=en_us&pg=1&pgSz=20&o=Relevance&flt=true"
    search_text: "SDE"
    target_titles:
      - "Software Engineer"

  - name: JPMC
    enabled: true
    parser: oracle_hcm
    url: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?keyword=Software+Engineer&location=United+States&locationId=300000000289738&locationLevel=country&mode=location"
    wait_ms: 12000
    target_titles:
      - "Software Engineer"

  - name: Goldman Sachs
    enabled: true
    parser: generic
    url: "https://higher.gs.com/results?LOCATION=Albany|New%20York|Atlanta|Austin|Dallas|Houston|Richardson|Boston|Chicago|Detroit|Troy|Draper|Salt%20Lake%20City|Jersey%20City|Los%20Angeles|Newport%20Beach|San%20Francisco|Miami|West%20Palm%20Beach|Philadelphia|Pittsburgh|Saint%20Louis|Seattle|Washington|Wilmington&page=1&search=software&sort=RELEVANCE"
    wait_ms: 8000
    target_titles:
      - "Software Engineer"

  - name: DoorDash
    enabled: true
    parser: generic
    url: "https://careersatdoordash.com/job-search/?keyword=software&location=&spage=1"
    wait_ms: 8000
    target_titles:
      - "Software Engineer"

  - name: Visa
    enabled: true
    parser: visa
    url: "https://corporate.visa.com/en/jobs/?q=software&cities=Ashburn&cities=Atlanta&cities=Austin&cities=Bellevue&cities=Denver&cities=Foster%20City&cities=Highlands%20Ranch&cities=Lehi&cities=Los%20Angeles&cities=Mentor&cities=Miami&cities=New%20York&cities=San%20Francisco&cities=Washington&cities=Wilmington"
    wait_ms: 10000
    target_titles:
      - "Software Engineer"

  - name: Spotify
    enabled: true
    parser: spotify
    url: "https://www.lifeatspotify.com/jobs?c=backend&c=data&c=machine-learning&c=mobile&c=security&c=web"
    categories: "backend,data,machine-learning,mobile,security,web"
    search_location: "usa"
    target_titles:
      - "Software Engineer"
      - "Backend Engineer"
      - "ML Engineer"
      - "Machine Learning Engineer"
      - "Fullstack Engineer"

  - name: Tesla
    enabled: true
    parser: generic
    url: "https://www.tesla.com/careers/search/?site=US"
    wait_ms: 10000
    target_titles:
      - "Software Engineer"

  - name: Stripe
    enabled: true
    parser: stripe
    url: "https://stripe.com/jobs/search?query=software&office_locations=North+America--Atlanta&office_locations=North+America--Chicago&office_locations=North+America--New+York&office_locations=North+America--San+Francisco+Bridge+HQ&office_locations=North+America--Seattle&office_locations=North+America--South+San+Francisco&office_locations=North+America--Washington+DC"
    target_titles:
      - "Software Engineer"

  - name: Oracle
    enabled: true
    parser: oracle_hcm
    url: "https://careers.oracle.com/en/sites/jobsearch/jobs?keyword=software&lastSelectedFacet=POSTING_DATES&location=United+States&locationId=300000000149325&mode=location&selectedFlexFieldsFacets=%22AttributeChar4%7CEmployee%7C%7CAttributeChar13%7CProfessional%22&selectedPostingDatesFacet=7"
    wait_ms: 12000
    target_titles:
      - "Software Engineer"
      - "Software Developer"
